name: Update Kick Leaderboard

on:
  schedule:
    # מריץ את האוטומציה בכל שעה עגולה
    - cron: '0 * * * *'
  workflow_dispatch: # הבורג החסר שפותח את הכפתור הידני!

permissions:
  contents: write # נותן לשרת אישור חיוני לכתוב ולשמור קבצים בחזרה לפרויקט שלך

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Leaderboard Script
      run: node INDEX.js

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        git commit -m "עדכון אוטומטי של הלידרבורד [skip ci]" || echo "אין שינויים חדשים בקובץ"
        git push
