name: Update Kick Leaderboard

on:
  schedule:
    # מריץ את האוטומציה בכל שעה עגולה
    - cron: '0 * * * *'
  workflow_dispatch: # הבורג החסר שפותח את הכפתור הידני!

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Leaderboard Script
      run: node INDEX.js
